### ISSUE TITLE
Define class and print methods for return objects?

### ISSUE THREAD

**Issue by cboettig** [cscheid/rgithub#17]
Thanks for an excellent implementation of the github API for R here.  

Just thinking that the output would be a little prettier if you defined a class for your standard return list (that has elements "ok", "content", headers", and "code").  Then one might add a few convenience methods for such an object so that it provides somewhat tidier output for the user.  

For instance, one might then have a print method for the object, such as this:

```coffee
print.github <- function(x, ...) sapply(x$content, function(x) cat(as.yaml(x[names(x) != "body"]), cat(x$body)))
```
(e.g. using things like `cat` and `yaml` formatting to make the output print more cleanly to the console for inspection).  

Likewise a `summary` method could offer a more condensed view.

**Comment by cscheid** [comment]
I'm going to close this until we find a yaml-less alternative. I still feel that it's too big a hammer for its payoff.
