### ISSUE TITLE
confusing that GitHub repo `rgithub` = R package `github`?

### ISSUE THREAD

**Issue by jennybc** [cscheid/rgithub#29]
Perhaps I am the only one to get tripped by this?

But since the repo is named `rgithub` and the package one will immediately want to load is `github`, maybe you should mention this in the `README.md`.

My install and explore sequence started like so:

```
> library(devtools)
> install_github("cscheid/rgithub")
Installing github repo cscheid/rgithub@master from cscheid
<blah blah blah>
> library(rgithub)
Error in library(rgithub) : there is no package called ‘rgithub’
<much puzzlement … listing my libraries … AHA!>
> library(github)
```

Looking forward to using the package!

**Comment by cscheid** [comment]
Picking this up.... @karthik, if I choose `roctopus` I'm going to get yelled at: http://www.rforge.net/ROctopus/index.html :)

**Comment by cscheid** [comment]
Just for completeness: `roctocat` is a non-starter not because of GitHub. *GitHub* allows libraries to use their trademarks, but CRAN's policy explicitly forbids it. It's precisely what bit me with `github`. I'm not inclined to go argue my case again to the CRAN police..

**Comment by karthik** [comment]
I don't know if CRAN complains about stuff on rforge! But yeah arguing with CRAN police is pointless.

http://cran.r-project.org/web/packages/ROctopus/index.html

:)

**Comment by cscheid** [comment]
Oh, in the case of `ROctopus`, it's @s-u who'll yell at me ;)

**Comment by jennybc** [comment]
@cscheid Is there any place exactly in, e.g. CRAN policies, that makes you think `rgithub` or `githubr` or whatever wouldn't fly? I care for the sake of this package and also my wrapper around Google Sheets. I mean, we have [`googleVis`](http://cran.r-project.org/web/packages/googleVis/index.html), after all!

**Comment by cscheid** [comment]
Um, there's a certain *someone* that controls the acceptance over at CRAN. And he gets the final say. And my submission got rejected. And I argued that there were no fewer than 28 other libraries using GitHub trademarks officially endorsed by GitHub. To no avail.

**Comment by jennybc** [comment]
Dear @mages and @jcheng,

Can you share any wisdom about getting `googleVis` onto CRAN with that name?

Thanks.

**Comment by karthik** [comment]
There is also leaflet going up soon for e.g.

**Comment by karthik** [comment]
@jennybc Here is the vague wording on the policies wrt trademarks.
http://marker.to/ntMRjh

**Comment by jennybc** [comment]
I have much respect for GitHub. And Google.

**Comment by mages** [comment]
Well, perhaps I got away with it because 'to google' is actually a verb in the [Oxford Dictionary](http://www.oxforddictionaries.com/definition/english/google) and googleVis is just a play on that.

**Comment by hadley** [comment]
:+1:

**Comment by cscheid** [comment]
Ok, any downvotes for `hubr`?

**Comment by soodoku** [comment]
grithub? gitr?

just checked: https://github.com/melix/grithub

**Comment by soodoku** [comment]
if you want to get cute, even hubby can work

**Comment by jennybc** [comment]
~~`gitr`~~ since there is [`git2r`](https://github.com/ropensci/git2r), another possibility is `github2r` ... but then you're back where you started w/ GitHub in the name 😕

**Comment by gordonwoodhull** [comment]
+1 for hubr. note that [rhub](https://github.com/r-hub/proposal) would also be a conflict (and not just with [the delicious chard](https://en.wikipedia.org/wiki/Rhubarb)).

**Comment by cscheid** [comment]
@jennybc: turns out @soodoku did suggest `grithub`. I like that one the best right now. I'll get started on this when I get back to Tucson.

**Comment by cscheid** [comment]
Move to #67.
