### ISSUE TITLE
Allowing for "git" to be an optional argument

### ISSUE THREAD

**Issue by aronlindberg** [cscheid/rgithub#45]
Currently the get.commit function reads:

`get.commit <- function(owner, repo, sha, ctx = get.github.context())`
`  .api.get.request(ctx, c("repos", owner, repo, "git", "commits", sha))`

However, "git" should be an optional argument, since:

https://api.github.com/repos/rubinius/rubinius/git/commits/2d762ce473a0a8a104d80e838a647eb67fa035d7

and

https://api.github.com/repos/rubinius/rubinius/commits/2d762ce473a0a8a104d80e838a647eb67fa035d7

return different things - the latter query gives a list of all the files attached to that commit which is very practical.

My dirty solution is to rewrite the function as such:

`get.commit <- function(owner, repo, sha, git, ctx = get.github.context())`
`  .api.get.request(ctx, c("repos", owner, repo, git, "commits", sha))`

Which allows you to call either:

`get.commit(git = NULL, ctx = get.github.context(), owner = "rubinius", repo = "rubinius", sha =` `"7ebdd693f1f3f9f194f4ee103f39795eb16b3610")`

or

`get.commit(git = "git", ctx = get.github.context(), owner = "rubinius", repo = "rubinius", sha =` `"7ebdd693f1f3f9f194f4ee103f39795eb16b3610")`

This is not a very elegant solution, but I currently don't know a better option - does anyone have a suggestion of a neater way to write it?

**Comment by cscheid** [comment]
`get.repository.commits` on `repositories.R` will give you exactly what you want here.

The naming convention for the library is (or at least it's meant to be :)), roughly, `httpverb.subfolder-of-github-documentation.entrypoint`. You probably didn't find it because of you were looking under "commits" instead of "repositories".
