### ISSUE TITLE
ead1c0d broke the package because GitHub doesn't accept vectors instead of scalars

### ISSUE THREAD

**Issue by s-u** [cscheid/rgithub#50]
By default `jsonlite` encodes scalars as vectors, so the resulting requests are invalid and thus GitHub rejects the requests. Example:

```r
> cat(rjson::toJSON(list(a="foo")),"\n")
{"a":"foo"} 
> cat(jsonlite::toJSON(list(a="foo")),"\n")
{"a":["foo"]} 
```

Either that change has to be reverted or `auto_unbox=TRUE` must be used with `jsonlite`.

**Comment by gordonwoodhull** [comment]
@s-u, did you test `auto_unbox=TRUE`? I am scared to upgrade rgithub because I have other work to do. I'm hoping we can submit a PR on this.

**Comment by s-u** [comment]
No, for the same reason (lack of time) I have simply reverted ead1c0d  in my fork. Eventually I plan to test `auto_unbox=TRUE` but I don't know when I get to it.
