### ISSUE TITLE
Differences between rgithub and octokit.rb?

### ISSUE THREAD

**Issue by aronlindberg** [cscheid/rgithub#51]
I have a question about the rgithub functionality. Using ruby and octokit.rb I can do things like the following:

    client = Octokit::Client.new :login => 'username', :password => 'password'
    pull = client.pull_request(repo, number)
    output = [pull.merged_at, pull.additions, pull.deletions, pull.commits, pull.changed_files]

Meaning that I can directly extract different fields from the JSON that I pull down using the API library. Is something similar possible using rgithub? Whenever I try to extract specific data from the output I end up using either something using `grepl()` or very complex subsetting of lists e.g. `output[[1]][2]$'filename'[[1]][1]` etc.

**Comment by cscheid** [comment]
This is less a `rgithub` problem and more an R problem in general. I designed `rgithub` to purposefully be "thin", and so it won't try to do anything fancy for you, especially in regards to parsing JSON. But perhaps you can look into something like [jsonlite](https://cran.r-project.org/web/packages/jsonlite/index.html), which I believe does something like what you want with the JSON output.

**Comment by aronlindberg** [comment]
Thanks, that's helpful. `rgithub`, however, seems to give me the output as lists. How can I coax it into outputting JSON so that I can use something like `jsonlite`?

**Comment by cscheid** [comment]
We get the output directly from `HTTR`, which does the parsing into lists itself. You'd have to coax HTTR into using a different `jsonlite` handler, and I'm not sure how to do that. In the worst case, you can unparse the lists back into a string, and then call jsonlite on it. Ugly, I know.

**Comment by aronlindberg** [comment]
Thanks again!
