### ISSUE TITLE
Use underscores instead of dots

### ISSUE THREAD

**Issue by hadley** [cscheid/rgithub#53]
Otherwise it looks like you're defining S3 methods

**Comment by cscheid** [comment]
There's no way to change this without breaking *everyone's* code, though. Maybe when we find a solution for #29, I'll go ahead and make the breaking change.

(In a related note, do you know how to make ESS not turn an underscore into `<-`? I know that typing it twice fixes it, but that's still very annoying.)

**Comment by soodoku** [comment]
Re. 2: http://stackoverflow.com/questions/1816238/how-to-turn-off-auto-replacement-in-emacs-speaks-statistics-for-r

**Comment by cscheid** [comment]
Closed (wontfix) by #70.
