### ISSUE TITLE
Register github app for this package

### ISSUE THREAD

**Issue by hadley** [cscheid/rgithub#54]
You don't need to have each user register their own app, and there's no problem with including the app key/secret in the package (the secret isn't actually a secret)

**Comment by cscheid** [comment]
Really? I thought it wasn't the case. I remember reading that GitHub uses the application info to know who's using it, and since different apps would presumably use `rgithub`, this would cause a nontrivial amount of confusion.

How did you get to this conclusion? (Link to a webpage is enough :))

**Comment by hadley** [comment]
I think basically you should think of an R package as a "app" - i.e. if it was a GUI application, you'd bundle the client key/secret in the app itself.

Came to this conclusion after talking to @craigcitro about oauth in google context.

**Comment by hadley** [comment]
Equally, I think it would be fine to deprecate this auth mechanism altogether and just use the PAT.

**Comment by cscheid** [comment]
The scenario I want to avoid is someone using `rgithub` inside their own application.

Is there a reliable way to detect if R is being used interactively?

**Comment by hadley** [comment]
`interactive()` :wink:
