### ISSUE TITLE
Pagination?

### ISSUE THREAD

**Issue by hadley** [cscheid/rgithub#56]
```R
library(dplyr)
library(github)
ctx <- interactive.login("56b637a5baffac62cad9", "8e107541ae1791259e9987d544ca568633da2ebf")

issues <- get.repository.issues("hadley", "dplyr")
length(issues$content)
```

I only get 30 issues - how do I get the remaining pages? (Obviously I could just crank up the `per_page` parameter which solves this problem, but it would be nice to have a general solution)

**Comment by gordonwoodhull** [comment]
Duplicate of #30
