### ISSUE TITLE
Rename to grithub

### ISSUE THREAD

**Issue by cscheid** [cscheid/rgithub#67]
We're going to rename the library `grithub`, and push it to CRAN.

**Comment by mbojan** [comment]
Yes please!

**Comment by saurfang** [comment]
Any blockers that prevent pushing this to CRAN anytime soon?

**Comment by cscheid** [comment]
The blocker is currently that I have only 24 hours in the day. I'm sorry :/

**Comment by cscheid** [comment]
Closed (wontfix) by #70.
