### ISSUE TITLE
Seeking future maintainer

### ISSUE THREAD

**Issue by cscheid** [cscheid/rgithub#70]
It's clear that I don't have the time to update this project to my satisfaction anymore. If you're interested in taking over, please reach out to me.

**Comment by jennybc** [comment]
I'm not in a position to take over maintenance, but I note that [gh](https://cran.r-project.org/package=gh) is in the same space and is on CRAN and we're quite committed to maintaining, if you are looking for places to refer people.

**Comment by cscheid** [comment]
@jennybc, `gh` looks fantastic. Do you mind if I essentially tell people to stop using this and point them to `gh` instead?

**Comment by jennybc** [comment]
That's fine! gh is very low-level, in the sense that one still has to read the API docs. So you might also want to mention @coatless's project <https://github.com/coatless/ghapi3> that provides another layer on top of gh. They complement each other.

**Comment by cscheid** [comment]
Great, thank you both! I updated the README to point people to both libraries. I'm actually happy with this outcome, and I think I now consider this library defunct.
